language: haxe

os:
    - linux
    - osx

sudo: false

haxe:
  - "3.2.1"
  - development

before_script:
  - cd ..
  - git clone https://github.com/tong/om.core.git
  - cd -

script:
    - haxe --cwd examples/bars/ build.hxml
    - haxe --cwd examples/black_and_red/ build.hxml
    - haxe --cwd examples/graphs/ build.hxml
    - haxe --cwd examples/hello/ build.hxml
