language: haxe

os:
    - linux
    - osx

sudo: false

haxe:
    - "3.4.2"
    - development

before_script:
    - cd ..
    - git clone https://github.com/tong/om.core.git
    - git clone https://github.com/tong/om.ease.git
    - cd -

script:
    - haxe --cwd examples/bars/ build.hxml
    - haxe --cwd examples/black_and_red/ build.hxml
    - haxe --cwd examples/graphs/ build.hxml
    - haxe --cwd examples/hello/ build.hxml
    #- haxe --cwd examples/nme/ build.hxml
