language: haxe

os:
    - linux
    - osx

sudo: false

haxe:
  - "3.2.1"
  - development

install:
    - git https://github.com/tong/om.core.git ../

script:
    - haxe --cwd examples/bars/ build.hxml
    - haxe --cwd examples/black_and_red/ build.hxml
    - haxe --cwd examples/graphs/ build.hxml
    - haxe --cwd examples/hello/ build.hxml
