language: haxe

os:
    - linux

haxe:
    - "3.4.2"
    - development

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib dev om.tween .

before_script:
    - cd ..
    - haxelib git om.core https://github.com/tong/om.core
    - haxelib git om.ease https://github.com/tong/om.ease
    - cd -

script:
    - haxe --cwd examples/bars/ build.hxml
    - haxe --cwd examples/black_and_red/ build.hxml
    - haxe --cwd examples/graphs/ build.hxml
    - haxe --cwd examples/hello/ build.hxml
    #- haxe --cwd examples/nme/ build.hxml
